INSERT INTO english_topics (id, name, category, description, difficulty, prompts, vocabulary, "grammarTips", "isActive", "order", "createdAt", "updatedAt") VALUES
('daily-coffee', 'Ordering Coffee', 'daily', 'Practice ordering at a coffee shop', 'BEGINNER', '["Hi, can I get a latte please?","What size would you like?","For here or to go?"]', 'latte, espresso, cappuccino', 'Use "I would like" for polite ordering', true, 1, NOW(), NOW()),
('daily-directions', 'Asking Directions', 'daily', 'Practice asking and giving directions', 'BEGINNER', '["Excuse me, how do I get to the station?","Turn left at the corner","Is it far from here?"]', 'turn left, go straight, corner', 'Use "Could you tell me" for polite questions', true, 2, NOW(), NOW()),
('daily-smalltalk', 'Small Talk', 'daily', 'Practice casual conversation', 'BEGINNER', '["How is your day going?","What do you do for fun?","Nice weather today, right?"]', 'weekend, hobby, weather', 'Use present continuous for ongoing actions', true, 3, NOW(), NOW()),
('work-interview', 'Job Interview', 'work', 'Practice job interview answers', 'INTERMEDIATE', '["Tell me about yourself","Why do you want this job?","What are your strengths?"]', 'experience, skill, teamwork', 'Use past tense for previous experiences', true, 4, NOW(), NOW()),
('work-meeting', 'Office Meeting', 'work', 'Practice speaking in meetings', 'INTERMEDIATE', '["Could I add something here?","I agree with your point","Let us move on to the next item"]', 'agenda, deadline, follow-up', 'Use "could" for polite suggestions', true, 5, NOW(), NOW()),
('travel-airport', 'Airport Check-in', 'travel', 'Practice airport conversations', 'BEGINNER', '["May I see your passport?","How many bags are you checking in?","Window or aisle seat?"]', 'boarding pass, gate, luggage', 'Use "May I" for polite requests', true, 6, NOW(), NOW()),
('travel-hotel', 'Hotel Booking', 'travel', 'Practice booking a hotel room', 'BEGINNER', '["I would like to book a room","Do you have any vacancies?","What time is check-out?"]', 'reservation, vacancy, check-in', 'Use "I would like to" for polite requests', true, 7, NOW(), NOW()),
('ielts-part1', 'IELTS Speaking Part 1', 'ielts', 'Practice IELTS Speaking Part 1', 'INTERMEDIATE', '["Do you work or study?","What do you like about your hometown?","How often do you use public transport?"]', 'hometown, commute, leisure', 'Answer in 2-3 sentences with examples', true, 8, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;