export interface SpeciesEntry { code: string; label: string; emoji: string; category: string; subcategory: string; }

export const SPECIES_CATEGORIES = [
  { key:"MAMMAL", label:"哺乳類", emoji:"🐾" },
  { key:"BIRD", label:"鳥類", emoji:"🐦" },
  { key:"REPTILE", label:"爬蟲類", emoji:"🦎" },
  { key:"AMPHIBIAN", label:"兩棲類", emoji:"🐸" },
  { key:"FISH", label:"魚類", emoji:"🐟" },
  { key:"INSECT", label:"昆蟲", emoji:"🦋" },
  { key:"ARACHNID", label:"蛛形綱", emoji:"🕷️" },
  { key:"CRUSTACEAN", label:"甲殼類", emoji:"🦀" },
  { key:"MOLLUSK", label:"軟體動物", emoji:"🐙" },
  { key:"ECHINODERM", label:"棘皮動物", emoji:"⭐" },
  { key:"CNIDARIAN", label:"刺胞動物", emoji:"🪼" },
  { key:"PLANT", label:"植物", emoji:"🌱" },
  { key:"FUNGI", label:"真菌", emoji:"🍄" },
  { key:"MYTHICAL", label:"神話傳說", emoji:"🐉" },
  { key:"EXTINCT", label:"古生物", emoji:"🦖" },
  { key:"OTHER", label:"其他", emoji:"🫧" },
];
export const ALL_SPECIES: SpeciesEntry[] = [
  {code:"WOLF_GRAY",label:"灰狼",emoji:"🐺",category:"MAMMAL",subcategory:"犬科"},
  {code:"FOX_RED",label:"赤狐",emoji:"🦊",category:"MAMMAL",subcategory:"犬科"},
  {code:"FOX_FENNEC",label:"耳廓狐",emoji:"🦊",category:"MAMMAL",subcategory:"犬科"},
  {code:"DOG_HUSKY",label:"哈士奇",emoji:"🐕",category:"MAMMAL",subcategory:"犬科"},
  {code:"DOG_SHIBA",label:"柴犬",emoji:"🐕",category:"MAMMAL",subcategory:"犬科"},
  {code:"DOG_CORGI",label:"柯基",emoji:"🐕",category:"MAMMAL",subcategory:"犬科"},
  {code:"JACKAL",label:"胡狼",emoji:"🐕",category:"MAMMAL",subcategory:"犬科"},
  {code:"COYOTE",label:"郊狼",emoji:"🐕",category:"MAMMAL",subcategory:"犬科"},
  {code:"CAT",label:"家貓",emoji:"🐱",category:"MAMMAL",subcategory:"貓科"},
  {code:"TIGER",label:"老虎",emoji:"🐯",category:"MAMMAL",subcategory:"貓科"},
  {code:"LION",label:"獅子",emoji:"🦁",category:"MAMMAL",subcategory:"貓科"},
  {code:"LEOPARD",label:"花豹",emoji:"🐆",category:"MAMMAL",subcategory:"貓科"},
  {code:"SNOW_LEOPARD",label:"雪豹",emoji:"🐆",category:"MAMMAL",subcategory:"貓科"},
  {code:"CHEETAH",label:"獵豹",emoji:"🐆",category:"MAMMAL",subcategory:"貓科"},
  {code:"JAGUAR",label:"美洲豹",emoji:"🐆",category:"MAMMAL",subcategory:"貓科"},
  {code:"LYNX",label:"猞猁",emoji:"🐱",category:"MAMMAL",subcategory:"貓科"},
  {code:"PUMA",label:"美洲獅",emoji:"🐱",category:"MAMMAL",subcategory:"貓科"},
  {code:"BEAR_BROWN",label:"棕熊",emoji:"🐻",category:"MAMMAL",subcategory:"熊科"},
  {code:"BEAR_POLAR",label:"北極熊",emoji:"🐻‍❄️",category:"MAMMAL",subcategory:"熊科"},
  {code:"BEAR_PANDA",label:"大熊貓",emoji:"🐼",category:"MAMMAL",subcategory:"熊科"},
  {code:"BEAR_BLACK",label:"黑熊",emoji:"🐻",category:"MAMMAL",subcategory:"熊科"},
  {code:"MONKEY",label:"獼猴",emoji:"🐒",category:"MAMMAL",subcategory:"靈長類"},
  {code:"GORILLA",label:"大猩猩",emoji:"🦍",category:"MAMMAL",subcategory:"靈長類"},
  {code:"CHIMPANZEE",label:"黑猩猩",emoji:"🐵",category:"MAMMAL",subcategory:"靈長類"},
  {code:"ORANGUTAN",label:"紅毛猩猩",emoji:"🦧",category:"MAMMAL",subcategory:"靈長類"},
  {code:"LEMUR",label:"狐猴",emoji:"🐒",category:"MAMMAL",subcategory:"靈長類"},
  {code:"ELEPHANT",label:"非洲象",emoji:"🐘",category:"MAMMAL",subcategory:"長鼻目"},
  {code:"RHINO",label:"犀牛",emoji:"🦏",category:"MAMMAL",subcategory:"奇蹄目"},
  {code:"HIPPO",label:"河馬",emoji:"🦛",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"GIRAFFE",label:"長頸鹿",emoji:"🦒",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"HORSE",label:"馬",emoji:"🐴",category:"MAMMAL",subcategory:"奇蹄目"},
  {code:"ZEBRA",label:"斑馬",emoji:"🦓",category:"MAMMAL",subcategory:"奇蹄目"},
  {code:"DEER",label:"鹿",emoji:"🦌",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"MOOSE",label:"駝鹿",emoji:"🦌",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"BISON",label:"美洲野牛",emoji:"🦬",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"COW",label:"牛",emoji:"🐄",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"SHEEP",label:"綿羊",emoji:"🐑",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"GOAT",label:"山羊",emoji:"🐐",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"PIG",label:"豬",emoji:"🐖",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"BOAR",label:"野豬",emoji:"🐗",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"CAMEL",label:"駱駝",emoji:"🐪",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"LLAMA",label:"羊駝",emoji:"🦙",category:"MAMMAL",subcategory:"偶蹄目"},
  {code:"RABBIT",label:"兔子",emoji:"🐰",category:"MAMMAL",subcategory:"兔形目"},
  {code:"SQUIRREL",label:"松鼠",emoji:"🐿️",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"MOUSE",label:"老鼠",emoji:"🐭",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"RAT",label:"大鼠",emoji:"🐀",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"HAMSTER",label:"倉鼠",emoji:"🐹",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"PORCUPINE",label:"豪豬",emoji:"🦔",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"HEDGEHOG",label:"刺蝟",emoji:"🦔",category:"MAMMAL",subcategory:"蝟形目"},
  {code:"BEAVER",label:"河狸",emoji:"🦫",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"CAPYBARA",label:"水豚",emoji:"🦫",category:"MAMMAL",subcategory:"囓齒目"},
  {code:"OTTER",label:"水獺",emoji:"🦦",category:"MAMMAL",subcategory:"鼬科"},
  {code:"BADGER",label:"獾",emoji:"🦡",category:"MAMMAL",subcategory:"鼬科"},
  {code:"SKUNK",label:"臭鼬",emoji:"🦨",category:"MAMMAL",subcategory:"鼬科"},
  {code:"RACCOON",label:"浣熊",emoji:"🦝",category:"MAMMAL",subcategory:"浣熊科"},
  {code:"RED_PANDA",label:"小熊貓",emoji:"🐾",category:"MAMMAL",subcategory:"小熊貓科"},
  {code:"KOALA",label:"無尾熊",emoji:"🐨",category:"MAMMAL",subcategory:"有袋類"},
  {code:"KANGAROO",label:"袋鼠",emoji:"🦘",category:"MAMMAL",subcategory:"有袋類"},
  {code:"SLOTH",label:"樹懶",emoji:"🦥",category:"MAMMAL",subcategory:"貧齒目"},
  {code:"ANTEATER",label:"食蟻獸",emoji:"🐜",category:"MAMMAL",subcategory:"貧齒目"},
  {code:"ARMADILLO",label:"犰狳",emoji:"🦔",category:"MAMMAL",subcategory:"貧齒目"},
  {code:"BAT",label:"蝙蝠",emoji:"🦇",category:"MAMMAL",subcategory:"翼手目"},
  {code:"FLYING_FOX",label:"狐蝠",emoji:"🦇",category:"MAMMAL",subcategory:"翼手目"},
  {code:"WHALE_BLUE",label:"藍鯨",emoji:"🐋",category:"MAMMAL",subcategory:"鯨豚類"},
  {code:"WHALE_KILLER",label:"虎鯨",emoji:"🐋",category:"MAMMAL",subcategory:"鯨豚類"},
  {code:"DOLPHIN",label:"海豚",emoji:"🐬",category:"MAMMAL",subcategory:"鯨豚類"},
  {code:"NARWHAL",label:"獨角鯨",emoji:"🐋",category:"MAMMAL",subcategory:"鯨豚類"},
  {code:"BELUGA",label:"白鯨",emoji:"🐋",category:"MAMMAL",subcategory:"鯨豚類"},
  {code:"SEAL",label:"海豹",emoji:"🦭",category:"MAMMAL",subcategory:"鰭足類"},
  {code:"SEA_LION",label:"海獅",emoji:"🦭",category:"MAMMAL",subcategory:"鰭足類"},
  {code:"WALRUS",label:"海象",emoji:"🦭",category:"MAMMAL",subcategory:"鰭足類"},
  {code:"PLATYPUS",label:"鴨嘴獸",emoji:"🦆",category:"MAMMAL",subcategory:"單孔目"},
{code:"EAGLE",label:"鷹",emoji:"🦅",category:"BIRD",subcategory:"猛禽"},
  {code:"HAWK",label:"隼",emoji:"🦅",category:"BIRD",subcategory:"猛禽"},
  {code:"FALCON",label:"遊隼",emoji:"🦅",category:"BIRD",subcategory:"猛禽"},
  {code:"OWL",label:"貓頭鷹",emoji:"🦉",category:"BIRD",subcategory:"猛禽"},
  {code:"VULTURE",label:"禿鷹",emoji:"🦅",category:"BIRD",subcategory:"猛禽"},
  {code:"CONDOR",label:"神鷹",emoji:"🦅",category:"BIRD",subcategory:"猛禽"},
  {code:"SWAN",label:"天鵝",emoji:"🦢",category:"BIRD",subcategory:"水鳥"},
  {code:"DUCK",label:"鴨",emoji:"🦆",category:"BIRD",subcategory:"水鳥"},
  {code:"FLAMINGO",label:"紅鶴",emoji:"🦩",category:"BIRD",subcategory:"水鳥"},
  {code:"PENGUIN",label:"企鵝",emoji:"🐧",category:"BIRD",subcategory:"水鳥"},
  {code:"SEAGULL",label:"海鷗",emoji:"🐦",category:"BIRD",subcategory:"水鳥"},
  {code:"PARROT",label:"鸚鵡",emoji:"🦜",category:"BIRD",subcategory:"攀禽"},
  {code:"MACAW",label:"金剛鸚鵡",emoji:"🦜",category:"BIRD",subcategory:"攀禽"},
  {code:"TOUCAN",label:"巨嘴鳥",emoji:"🦜",category:"BIRD",subcategory:"攀禽"},
  {code:"WOODPECKER",label:"啄木鳥",emoji:"🐦",category:"BIRD",subcategory:"攀禽"},
  {code:"HUMMINGBIRD",label:"蜂鳥",emoji:"🐦",category:"BIRD",subcategory:"鳴禽"},
  {code:"SPARROW",label:"麻雀",emoji:"🐦",category:"BIRD",subcategory:"鳴禽"},
  {code:"CROW",label:"烏鴉",emoji:"🐦‍⬛",category:"BIRD",subcategory:"鳴禽"},
  {code:"RAVEN",label:"渡鴉",emoji:"🐦‍⬛",category:"BIRD",subcategory:"鳴禽"},
  {code:"PEACOCK",label:"孔雀",emoji:"🦚",category:"BIRD",subcategory:"陸禽"},
  {code:"CHICKEN",label:"雞",emoji:"🐔",category:"BIRD",subcategory:"陸禽"},
  {code:"TURKEY",label:"火雞",emoji:"🦃",category:"BIRD",subcategory:"陸禽"},
  {code:"OSTRICH",label:"鴕鳥",emoji:"🦖",category:"BIRD",subcategory:"走禽"},
  {code:"EMU",label:"鴯鶓",emoji:"🦖",category:"BIRD",subcategory:"走禽"},
  {code:"DODO",label:"渡渡鳥",emoji:"🐦",category:"BIRD",subcategory:"已滅絕"},
  {code:"PIGEON",label:"鴿子",emoji:"🕊️",category:"BIRD",subcategory:"鳴禽"},
  {code:"SNAKE",label:"蛇",emoji:"🐍",category:"REPTILE",subcategory:"蛇類"},
  {code:"SNAKE_COBRA",label:"眼鏡蛇",emoji:"🐍",category:"REPTILE",subcategory:"蛇類"},
  {code:"SNAKE_RATTLER",label:"響尾蛇",emoji:"🐍",category:"REPTILE",subcategory:"蛇類"},
  {code:"GECKO",label:"壁虎",emoji:"🦎",category:"REPTILE",subcategory:"蜥蜴"},
  {code:"CHAMELEON",label:"變色龍",emoji:"🦎",category:"REPTILE",subcategory:"蜥蜴"},
  {code:"IGUANA",label:"鬣蜥",emoji:"🦎",category:"REPTILE",subcategory:"蜥蜴"},
  {code:"KOMODO",label:"科摩多巨蜥",emoji:"🦎",category:"REPTILE",subcategory:"蜥蜴"},
  {code:"TURTLE_SEA",label:"海龜",emoji:"🐢",category:"REPTILE",subcategory:"龜類"},
  {code:"TURTLE",label:"陸龜",emoji:"🐢",category:"REPTILE",subcategory:"龜類"},
  {code:"CROCODILE",label:"鱷魚",emoji:"🐊",category:"REPTILE",subcategory:"鱷類"},
  {code:"ALLIGATOR",label:"短吻鱷",emoji:"🐊",category:"REPTILE",subcategory:"鱷類"},
  {code:"FROG_TREE",label:"樹蛙",emoji:"🐸",category:"AMPHIBIAN",subcategory:"蛙類"},
  {code:"FROG_DART",label:"毒箭蛙",emoji:"🐸",category:"AMPHIBIAN",subcategory:"蛙類"},
  {code:"TOAD",label:"蟾蜍",emoji:"🐸",category:"AMPHIBIAN",subcategory:"蛙類"},
  {code:"SALAMANDER",label:"蠑螈",emoji:"🦎",category:"AMPHIBIAN",subcategory:"有尾目"},
  {code:"AXOLOTL",label:"美西螈",emoji:"🦎",category:"AMPHIBIAN",subcategory:"有尾目"},
  {code:"CLOWNFISH",label:"小丑魚",emoji:"🐠",category:"FISH",subcategory:"海水魚"},
  {code:"BETTA",label:"鬥魚",emoji:"🐠",category:"FISH",subcategory:"淡水魚"},
  {code:"GOLDFISH",label:"金魚",emoji:"🐠",category:"FISH",subcategory:"淡水魚"},
  {code:"KOI",label:"錦鯉",emoji:"🐟",category:"FISH",subcategory:"淡水魚"},
  {code:"SALMON",label:"鮭魚",emoji:"🐟",category:"FISH",subcategory:"迴游魚"},
  {code:"TUNA",label:"鮪魚",emoji:"🐟",category:"FISH",subcategory:"海水魚"},
  {code:"SWORDFISH",label:"劍魚",emoji:"🐟",category:"FISH",subcategory:"海水魚"},
  {code:"MANTA",label:"蝠鱝",emoji:"🦈",category:"FISH",subcategory:"鰩類"},
  {code:"STINGRAY",label:"魟魚",emoji:"🦈",category:"FISH",subcategory:"鰩類"},
  {code:"SHARK",label:"大白鯊",emoji:"🦈",category:"FISH",subcategory:"鯊魚"},
  {code:"SHARK_HAMMER",label:"槌頭鯊",emoji:"🦈",category:"FISH",subcategory:"鯊魚"},
  {code:"SHARK_WHALE",label:"鯨鯊",emoji:"🦈",category:"FISH",subcategory:"鯊魚"},
  {code:"EEL",label:"海鱔",emoji:"🐍",category:"FISH",subcategory:"鰻魚"},
  {code:"EEL_ELECTRIC",label:"電鰻",emoji:"⚡",category:"FISH",subcategory:"鰻魚"},
  {code:"SEAHORSE",label:"海馬",emoji:"🦑",category:"FISH",subcategory:"特殊"},
  {code:"BLOWFISH",label:"河豚",emoji:"🐡",category:"FISH",subcategory:"特殊"},
  {code:"LIONFISH",label:"獅子魚",emoji:"🐡",category:"FISH",subcategory:"海水魚"},
  {code:"PIRANHA",label:"食人魚",emoji:"🐟",category:"FISH",subcategory:"淡水魚"},
  {code:"AROWANA",label:"龍魚",emoji:"🐲",category:"FISH",subcategory:"淡水魚"},
{code:"BUTTERFLY",label:"帝王蝶",emoji:"🦋",category:"INSECT",subcategory:"蝴蝶"},
  {code:"BUTTERFLY_MORPHO",label:"閃蝶",emoji:"🦋",category:"INSECT",subcategory:"蝴蝶"},
  {code:"MOTH_LUNA",label:"月神蛾",emoji:"🦋",category:"INSECT",subcategory:"蛾"},
  {code:"BEETLE_HERCULES",label:"大兜蟲",emoji:"🪲",category:"INSECT",subcategory:"甲蟲"},
  {code:"BEETLE_STAG",label:"鍬形蟲",emoji:"🪲",category:"INSECT",subcategory:"甲蟲"},
  {code:"BEETLE_RHINO",label:"獨角仙",emoji:"🪲",category:"INSECT",subcategory:"甲蟲"},
  {code:"LADYBUG",label:"瓢蟲",emoji:"🐞",category:"INSECT",subcategory:"甲蟲"},
  {code:"FIREFLY",label:"螢火蟲",emoji:"🪲",category:"INSECT",subcategory:"甲蟲"},
  {code:"BEE",label:"蜜蜂",emoji:"🐝",category:"INSECT",subcategory:"蜂"},
  {code:"WASP",label:"黃蜂",emoji:"🐝",category:"INSECT",subcategory:"蜂"},
  {code:"ANT",label:"螞蟻",emoji:"🐜",category:"INSECT",subcategory:"蟻"},
  {code:"DRAGONFLY",label:"蜻蜓",emoji:"🪰",category:"INSECT",subcategory:"蜻蜓"},
  {code:"GRASSHOPPER",label:"蚱蜢",emoji:"🦗",category:"INSECT",subcategory:"直翅目"},
  {code:"CRICKET",label:"蟋蟀",emoji:"🦗",category:"INSECT",subcategory:"直翅目"},
  {code:"MANTIS",label:"螳螂",emoji:"🦗",category:"INSECT",subcategory:"螳螂"},
  {code:"CICADA",label:"蟬",emoji:"🦗",category:"INSECT",subcategory:"半翅目"},
  {code:"CATERPILLAR",label:"毛蟲",emoji:"🐛",category:"INSECT",subcategory:"幼蟲"},
  {code:"MOSQUITO",label:"蚊子",emoji:"🦟",category:"INSECT",subcategory:"雙翅目"},
  {code:"FLY",label:"蒼蠅",emoji:"🪰",category:"INSECT",subcategory:"雙翅目"},
  {code:"COCKROACH",label:"蟑螂",emoji:"🪳",category:"INSECT",subcategory:"蜚蠊目"},
  {code:"SPIDER_TARANTULA",label:"捕鳥蛛",emoji:"🕷️",category:"ARACHNID",subcategory:"蜘蛛"},
  {code:"SPIDER_BLACK_WIDOW",label:"黑寡婦",emoji:"🕷️",category:"ARACHNID",subcategory:"蜘蛛"},
  {code:"SPIDER_JUMPING",label:"蠅虎",emoji:"🕷️",category:"ARACHNID",subcategory:"蜘蛛"},
  {code:"SCORPION",label:"蠍子",emoji:"🦂",category:"ARACHNID",subcategory:"蠍"},
  {code:"TICK",label:"蜱蟲",emoji:"🕷️",category:"ARACHNID",subcategory:"蜱"},
  {code:"CRAB",label:"螃蟹",emoji:"🦀",category:"CRUSTACEAN",subcategory:"蟹"},
  {code:"CRAB_COCONUT",label:"椰子蟹",emoji:"🦀",category:"CRUSTACEAN",subcategory:"蟹"},
  {code:"CRAB_HERMIT",label:"寄居蟹",emoji:"🦀",category:"CRUSTACEAN",subcategory:"蟹"},
  {code:"LOBSTER",label:"龍蝦",emoji:"🦞",category:"CRUSTACEAN",subcategory:"蝦"},
  {code:"SHRIMP",label:"蝦",emoji:"🦐",category:"CRUSTACEAN",subcategory:"蝦"},
  {code:"CRAYFISH",label:"螯蝦",emoji:"🦞",category:"CRUSTACEAN",subcategory:"蝦"},
  {code:"ISOPOD",label:"大王具足蟲",emoji:"🦞",category:"CRUSTACEAN",subcategory:"等足類"},
  {code:"SQUID",label:"魷魚",emoji:"🦑",category:"MOLLUSK",subcategory:"頭足類"},
  {code:"OCTOPUS",label:"章魚",emoji:"🐙",category:"MOLLUSK",subcategory:"頭足類"},
  {code:"CUTTLEFISH",label:"墨魚",emoji:"🦑",category:"MOLLUSK",subcategory:"頭足類"},
  {code:"NAUTILUS",label:"鸚鵡螺",emoji:"🐚",category:"MOLLUSK",subcategory:"頭足類"},
  {code:"SNAIL",label:"蝸牛",emoji:"🐌",category:"MOLLUSK",subcategory:"腹足類"},
  {code:"SLUG",label:"蛞蝓",emoji:"🐌",category:"MOLLUSK",subcategory:"腹足類"},
  {code:"CLAM",label:"蛤蜊",emoji:"🦪",category:"MOLLUSK",subcategory:"雙殼類"},
  {code:"OYSTER",label:"牡蠣",emoji:"🦪",category:"MOLLUSK",subcategory:"雙殼類"},
  {code:"STARFISH",label:"海星",emoji:"⭐",category:"ECHINODERM",subcategory:"海星"},
  {code:"SEA_URCHIN",label:"海膽",emoji:"🦔",category:"ECHINODERM",subcategory:"海膽"},
  {code:"SEA_CUCUMBER",label:"海參",emoji:"🦔",category:"ECHINODERM",subcategory:"海參"},
  {code:"JELLYFISH",label:"水母",emoji:"🪼",category:"CNIDARIAN",subcategory:"水母"},
  {code:"ANEMONE",label:"海葵",emoji:"🌸",category:"CNIDARIAN",subcategory:"海葵"},
  {code:"CORAL",label:"珊瑚",emoji:"🪸",category:"CNIDARIAN",subcategory:"珊瑚"},
  {code:"EARTHWORM",label:"蚯蚓",emoji:"🪱",category:"OTHER",subcategory:"環節動物"},
  {code:"LEECH",label:"水蛭",emoji:"🪱",category:"OTHER",subcategory:"環節動物"},
  {code:"TARDIGRADE",label:"水熊蟲",emoji:"🐻",category:"OTHER",subcategory:"緩步動物"},
  {code:"SPONGE",label:"海綿",emoji:"🧽",category:"OTHER",subcategory:"海綿動物"},
{code:"ROSE",label:"玫瑰",emoji:"🌹",category:"PLANT",subcategory:"花卉"},
  {code:"SUNFLOWER",label:"向日葵",emoji:"🌻",category:"PLANT",subcategory:"花卉"},
  {code:"CHERRY_BLOSSOM",label:"櫻花",emoji:"🌸",category:"PLANT",subcategory:"花卉"},
  {code:"LOTUS",label:"蓮花",emoji:"🪷",category:"PLANT",subcategory:"花卉"},
  {code:"TULIP",label:"鬱金香",emoji:"🌷",category:"PLANT",subcategory:"花卉"},
  {code:"LAVENDER",label:"薰衣草",emoji:"💜",category:"PLANT",subcategory:"花卉"},
  {code:"CACTUS",label:"仙人掌",emoji:"🌵",category:"PLANT",subcategory:"多肉"},
  {code:"TREE_OAK",label:"橡樹",emoji:"🌳",category:"PLANT",subcategory:"樹木"},
  {code:"TREE_PINE",label:"松樹",emoji:"🌲",category:"PLANT",subcategory:"樹木"},
  {code:"TREE_PALM",label:"棕櫚樹",emoji:"🌴",category:"PLANT",subcategory:"樹木"},
  {code:"BAMBOO",label:"竹子",emoji:"🎋",category:"PLANT",subcategory:"禾本"},
  {code:"IVY",label:"常春藤",emoji:"🌿",category:"PLANT",subcategory:"藤本"},
  {code:"FERN",label:"蕨類",emoji:"🌿",category:"PLANT",subcategory:"蕨類"},
  {code:"MOSS",label:"苔蘚",emoji:"🟢",category:"PLANT",subcategory:"苔蘚"},
  {code:"VENUS_FLYTRAP",label:"捕蠅草",emoji:"🪴",category:"PLANT",subcategory:"食蟲植物"},
  {code:"MUSHROOM",label:"紅菇",emoji:"🍄",category:"FUNGI",subcategory:"菇類"},
  {code:"TRUFFLE",label:"松露",emoji:"🍄",category:"FUNGI",subcategory:"地下真菌"},
  {code:"SLIME_MOLD",label:"黏菌",emoji:"🟡",category:"FUNGI",subcategory:"黏菌"},
  {code:"LICHEN",label:"地衣",emoji:"🪨",category:"FUNGI",subcategory:"地衣"},
  {code:"TREX",label:"暴龍",emoji:"🦖",category:"EXTINCT",subcategory:"恐龍"},
  {code:"TRICERATOPS",label:"三角龍",emoji:"🦖",category:"EXTINCT",subcategory:"恐龍"},
  {code:"STEGOSAURUS",label:"劍龍",emoji:"🦖",category:"EXTINCT",subcategory:"恐龍"},
  {code:"BRACHIOSAURUS",label:"腕龍",emoji:"🦕",category:"EXTINCT",subcategory:"恐龍"},
  {code:"VELOCIRAPTOR",label:"迅猛龍",emoji:"🦖",category:"EXTINCT",subcategory:"恐龍"},
  {code:"PTERODACTYL",label:"翼手龍",emoji:"🦖",category:"EXTINCT",subcategory:"翼龍"},
  {code:"MAMMOTH",label:"猛獁象",emoji:"🐘",category:"EXTINCT",subcategory:"冰河期"},
  {code:"SABERTOOTH",label:"劍齒虎",emoji:"🐯",category:"EXTINCT",subcategory:"冰河期"},
  {code:"MEGALODON",label:"巨齒鯊",emoji:"🦈",category:"EXTINCT",subcategory:"史前魚類"},
  {code:"AMMONITE",label:"菊石",emoji:"🐚",category:"EXTINCT",subcategory:"史前軟體"},
  {code:"TRILOBITE",label:"三葉蟲",emoji:"🦞",category:"EXTINCT",subcategory:"史前節肢"},
  {code:"ANOMALOCARIS",label:"奇蝦",emoji:"🦐",category:"EXTINCT",subcategory:"寒武紀"},
  {code:"DRAGON",label:"火龍",emoji:"🐉",category:"MYTHICAL",subcategory:"龍"},
  {code:"DRAGON_ICE",label:"冰龍",emoji:"🐉",category:"MYTHICAL",subcategory:"龍"},
  {code:"PHOENIX",label:"鳳凰",emoji:"🐦‍🔥",category:"MYTHICAL",subcategory:"神鳥"},
  {code:"UNICORN",label:"獨角獸",emoji:"🦄",category:"MYTHICAL",subcategory:"神獸"},
  {code:"PEGASUS",label:"天馬",emoji:"🦄",category:"MYTHICAL",subcategory:"神獸"},
  {code:"KIRIN",label:"麒麟",emoji:"🦄",category:"MYTHICAL",subcategory:"神獸"},
  {code:"GRIFFIN",label:"獅鷲",emoji:"🦅",category:"MYTHICAL",subcategory:"合成獸"},
  {code:"CHIMERA",label:"奇美拉",emoji:"🐉",category:"MYTHICAL",subcategory:"合成獸"},
  {code:"HYDRA",label:"九頭蛇",emoji:"🐍",category:"MYTHICAL",subcategory:"怪物"},
  {code:"KRAKEN",label:"挪威海怪",emoji:"🐙",category:"MYTHICAL",subcategory:"海怪"},
  {code:"MERMAID",label:"美人魚",emoji:"🧜‍♀️",category:"MYTHICAL",subcategory:"人魚"},
  {code:"WEREWOLF",label:"狼人",emoji:"🐺",category:"MYTHICAL",subcategory:"變身獸"},
  {code:"VAMPIRE",label:"吸血鬼",emoji:"🧛",category:"MYTHICAL",subcategory:"不死族"},
  {code:"GOBLIN",label:"哥布林",emoji:"👺",category:"MYTHICAL",subcategory:"妖精"},
  {code:"FAIRY",label:"仙子",emoji:"🧚",category:"MYTHICAL",subcategory:"妖精"},
  {code:"CENTAUR",label:"半人馬",emoji:"🐴",category:"MYTHICAL",subcategory:"合成獸"},
  {code:"MINOTAUR",label:"牛頭人",emoji:"🐂",category:"MYTHICAL",subcategory:"合成獸"},
  {code:"SLIME",label:"史萊姆",emoji:"🫧",category:"MYTHICAL",subcategory:"奇幻"},
  {code:"GHOST",label:"幽靈",emoji:"👻",category:"MYTHICAL",subcategory:"不死族"},
  {code:"ELEMENTAL",label:"元素精靈",emoji:"✨",category:"MYTHICAL",subcategory:"精靈"},
];
export const SPECIES_EMOJI: Record<string, string> = Object.fromEntries(
  ALL_SPECIES.map(s => [s.code, s.emoji])
);

export const SPECIES_LABELS: Record<string, string> = Object.fromEntries(
  ALL_SPECIES.map(s => [s.code, s.label])
);

export function getSpeciesByCategory(cat: string) {
  return ALL_SPECIES.filter(s => s.category === cat);
}