// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nightasaur Team

/**
 * IELTS 雅思字彙題庫 (Part 1/2)
 * 每字彙含：英文/繁體中文/簡體中文/日文/詞性/難度
 * 題型：選正確定義、選字彙、選詞性、選同義字
 */

export interface IeltsWord {
  word: string;
  pos: string;
  zhTW: string;
  zhCN: string;
  ja: string;
  definition: string;
  example: string;
  synonym?: string;
  band: number;
  topic: string;
}

export const IELTS_WORDS: IeltsWord[] = [
  // 環境
  { word: "sustainability", pos: "n.", zhTW: "永續性", zhCN: "可持续性", ja: "持続可能性",
    definition: "ability to maintain without depleting resources",
    example: "The company focuses on sustainability.", synonym: "durability", band: 7, topic: "environment" },
  { word: "renewable", pos: "adj.", zhTW: "可再生的", zhCN: "可再生的", ja: "再生可能な",
    definition: "able to be replaced by natural processes",
    example: "Renewable energy is essential.", synonym: "sustainable", band: 6, topic: "environment" },
  { word: "emission", pos: "n.", zhTW: "排放", zhCN: "排放", ja: "排出",
    definition: "the discharge of gas or radiation",
    example: "Carbon emissions cause climate change.", synonym: "discharge", band: 6, topic: "environment" },
  { word: "biodiversity", pos: "n.", zhTW: "生物多樣性", zhCN: "生物多样性", ja: "生物多様性",
    definition: "variety of life in a habitat",
    example: "Rainforests have rich biodiversity.", synonym: "variety", band: 7, topic: "environment" },
  { word: "deforestation", pos: "n.", zhTW: "森林砍伐", zhCN: "森林砍伐", ja: "森林伐採",
    definition: "clearing of wide areas of trees",
    example: "Deforestation destroys habitats.", synonym: "clearance", band: 7, topic: "environment" },
  { word: "contaminate", pos: "v.", zhTW: "污染", zhCN: "污染", ja: "汚染する",
    definition: "to make impure with harmful substances",
    example: "Waste can contaminate rivers.", synonym: "pollute", band: 6, topic: "environment" },
  { word: "ecosystem", pos: "n.", zhTW: "生態系統", zhCN: "生态系统", ja: "生態系",
    definition: "community of organisms interacting with environment",
    example: "Coral reefs are fragile ecosystems.", synonym: "biome", band: 6, topic: "environment" },
  { word: "conservation", pos: "n.", zhTW: "保育", zhCN: "保护", ja: "保護",
    definition: "preservation of natural resources",
    example: "Wildlife conservation is urgent.", synonym: "preservation", band: 6, topic: "environment" },
// 科技
  { word: "innovation", pos: "n.", zhTW: "創新", zhCN: "创新", ja: "革新",
    definition: "a new method or idea", example: "Tech innovation drives growth.",
    synonym: "invention", band: 7, topic: "technology" },
  { word: "artificial", pos: "adj.", zhTW: "人工的", zhCN: "人工的", ja: "人工の",
    definition: "made by humans, not natural", example: "AI is transforming industries.",
    synonym: "synthetic", band: 6, topic: "technology" },
  { word: "automation", pos: "n.", zhTW: "自動化", zhCN: "自动化", ja: "自動化",
    definition: "machines doing work without humans", example: "Automation boosts productivity.",
    synonym: "mechanization", band: 7, topic: "technology" },
  { word: "digital", pos: "adj.", zhTW: "數位的", zhCN: "数字的", ja: "デジタル",
    definition: "relating to electronic tech", example: "The digital revolution changed communication.",
    synonym: "electronic", band: 5, topic: "technology" },
  { word: "efficient", pos: "adj.", zhTW: "有效率的", zhCN: "有效率的", ja: "効率的",
    definition: "max output with minimum waste", example: "Solar panels are more efficient.",
    synonym: "effective", band: 6, topic: "technology" },
  { word: "device", pos: "n.", zhTW: "裝置", zhCN: "设备", ja: "装置",
    definition: "a tool for a purpose", example: "Smartphones are essential devices.",
    synonym: "gadget", band: 5, topic: "technology" },
  { word: "obsolete", pos: "adj.", zhTW: "過時的", zhCN: "过时的", ja: "時代遅れ",
    definition: "no longer in use", example: "Old tech becomes obsolete quickly.",
    synonym: "outdated", band: 7, topic: "technology" },
  { word: "breakthrough", pos: "n.", zhTW: "突破", zhCN: "突破", ja: "画期的進歩",
    definition: "sudden important discovery", example: "A medical breakthrough saved lives.",
    synonym: "discovery", band: 7, topic: "technology" },
// 教育
  { word: "curriculum", pos: "n.", zhTW: "課程", zhCN: "课程", ja: "カリキュラム",
    definition: "subjects in a course of study", example: "The school updated its curriculum.",
    synonym: "syllabus", band: 7, topic: "education" },
  { word: "literacy", pos: "n.", zhTW: "讀寫能力", zhCN: "读写能力", ja: "リテラシー",
    definition: "ability to read and write", example: "Literacy is a national priority.",
    synonym: "reading skill", band: 7, topic: "education" },
  { word: "academic", pos: "adj.", zhTW: "學術的", zhCN: "学术的", ja: "学術の",
    definition: "relating to education and research", example: "She has an academic background.",
    synonym: "scholarly", band: 6, topic: "education" },
  { word: "assessment", pos: "n.", zhTW: "評估", zhCN: "评估", ja: "評価",
    definition: "evaluation of performance", example: "Assessment helps track progress.",
    synonym: "evaluation", band: 6, topic: "education" },
  { word: "tuition", pos: "n.", zhTW: "學費", zhCN: "学费", ja: "授業料",
    definition: "money charged for teaching", example: "Tuition has risen sharply.",
    synonym: "fees", band: 6, topic: "education" },
  { word: "compulsory", pos: "adj.", zhTW: "強制的", zhCN: "强制的", ja: "義務",
    definition: "required by rule or law", example: "Education is compulsory.",
    synonym: "mandatory", band: 7, topic: "education" },
  { word: "scholarship", pos: "n.", zhTW: "獎學金", zhCN: "奖学金", ja: "奨学金",
    definition: "financial aid for academic merit",
    example: "She won a scholarship.", synonym: "grant", band: 6, topic: "education" },
  { word: "pedagogy", pos: "n.", zhTW: "教學法", zhCN: "教学法", ja: "教育学",
    definition: "method of teaching", example: "Modern pedagogy emphasizes interaction.",
    synonym: "teaching method", band: 8, topic: "education" },
// 健康
  { word: "nutrition", pos: "n.", zhTW: "營養", zhCN: "营养", ja: "栄養",
    definition: "food necessary for health", example: "Nutrition is vital for children.",
    synonym: "nourishment", band: 6, topic: "health" },
  { word: "obesity", pos: "n.", zhTW: "肥胖", zhCN: "肥胖", ja: "肥満",
    definition: "being extremely overweight", example: "Childhood obesity is a concern.",
    synonym: "overweight", band: 7, topic: "health" },
  { word: "chronic", pos: "adj.", zhTW: "慢性的", zhCN: "慢性的", ja: "慢性の",
    definition: "lasting a long time (illness)", example: "Chronic pain affects many people.",
    synonym: "persistent", band: 7, topic: "health" },
  { word: "prevention", pos: "n.", zhTW: "預防", zhCN: "预防", ja: "予防",
    definition: "stopping something before it happens", example: "Prevention is better than cure.",
    synonym: "deterrence", band: 6, topic: "health" },
  { word: "epidemic", pos: "n.", zhTW: "流行病", zhCN: "流行病", ja: "流行病",
    definition: "widespread infectious disease", example: "The flu epidemic spread fast.",
    synonym: "outbreak", band: 7, topic: "health" },
  { word: "wellbeing", pos: "n.", zhTW: "身心健康", zhCN: "身心健康", ja: "健康",
    definition: "state of being healthy and happy",
    example: "Exercise improves mental wellbeing.", synonym: "welfare", band: 6, topic: "health" },
  { word: "therapy", pos: "n.", zhTW: "療法", zhCN: "疗法", ja: "治療法",
    definition: "treatment to relieve a disorder",
    example: "Physical therapy helped his recovery.", synonym: "treatment", band: 6, topic: "health" },
  { word: "sedentary", pos: "adj.", zhTW: "久坐的", zhCN: "久坐的", ja: "座りがち",
    definition: "involving little activity", example: "A sedentary lifestyle is unhealthy.",
    synonym: "inactive", band: 8, topic: "health" },
// 社會
  { word: "demographic", pos: "adj.", zhTW: "人口的", zhCN: "人口的", ja: "人口統計の",
    definition: "relating to population", example: "Demographic changes affect economies.",
    synonym: "population", band: 8, topic: "society" },
  { word: "urbanization", pos: "n.", zhTW: "都市化", zhCN: "城市化", ja: "都市化",
    definition: "shift of population to cities", example: "Urbanization is accelerating globally.",
    synonym: "urban development", band: 7, topic: "society" },
  { word: "inequality", pos: "n.", zhTW: "不平等", zhCN: "不平等", ja: "不平等",
    definition: "lack of equality", example: "Income inequality is growing.",
    synonym: "disparity", band: 7, topic: "society" },
  { word: "migration", pos: "n.", zhTW: "移民", zhCN: "移民", ja: "移住",
    definition: "movement of people between places", example: "Migration shapes global culture.",
    synonym: "relocation", band: 6, topic: "society" },
  { word: "infrastructure", pos: "n.", zhTW: "基礎設施", zhCN: "基础设施", ja: "インフラ",
    definition: "basic physical structures for society",
    example: "The city needs better infrastructure.", synonym: "facilities", band: 7, topic: "society" },
  { word: "globalization", pos: "n.", zhTW: "全球化", zhCN: "全球化", ja: "グローバル化",
    definition: "interconnection of world economies",
    example: "Globalization connects markets.", synonym: "integration", band: 7, topic: "society" },
  { word: "poverty", pos: "n.", zhTW: "貧困", zhCN: "贫困", ja: "貧困",
    definition: "state of being extremely poor", example: "Poverty affects education.",
    synonym: "destitution", band: 6, topic: "society" },
  { word: "multicultural", pos: "adj.", zhTW: "多元文化的", zhCN: "多元文化的", ja: "多文化の",
    definition: "relating to multiple cultures", example: "London is a multicultural city.",
    synonym: "diverse", band: 7, topic: "society" },

  // 經濟
  { word: "inflation", pos: "n.", zhTW: "通貨膨脹", zhCN: "通货膨胀", ja: "インフレ",
    definition: "general increase in prices", example: "Inflation reduces purchasing power.",
    synonym: "price rise", band: 7, topic: "economy" },
  { word: "recession", pos: "n.", zhTW: "經濟衰退", zhCN: "经济衰退", ja: "不況",
    definition: "decline in economic activity", example: "The recession caused job losses.",
    synonym: "downturn", band: 7, topic: "economy" },
  { word: "investment", pos: "n.", zhTW: "投資", zhCN: "投资", ja: "投資",
    definition: "putting money in for profit", example: "Investment in education pays off.",
    synonym: "funding", band: 6, topic: "economy" },
  { word: "consumption", pos: "n.", zhTW: "消費", zhCN: "消费", ja: "消費",
    definition: "using up goods and services", example: "Excessive consumption harms nature.",
    synonym: "usage", band: 6, topic: "economy" },
  { word: "commerce", pos: "n.", zhTW: "商業", zhCN: "商业", ja: "商業",
    definition: "buying and selling", example: "E-commerce is growing rapidly.",
    synonym: "trade", band: 6, topic: "economy" },
  { word: "subsidy", pos: "n.", zhTW: "補貼", zhCN: "补贴", ja: "補助金",
    definition: "government financial support",
    example: "Farmers receive subsidies.", synonym: "grant", band: 8, topic: "economy" },
  { word: "productivity", pos: "n.", zhTW: "生產力", zhCN: "生产力", ja: "生産性",
    definition: "rate of output per input", example: "Technology improves productivity.",
    synonym: "efficiency", band: 7, topic: "economy" },
  { word: "entrepreneur", pos: "n.", zhTW: "企業家", zhCN: "企业家", ja: "起業家",
    definition: "someone who starts businesses",
    example: "Entrepreneurs drive innovation.", synonym: "founder", band: 7, topic: "economy" },
];